import type { DocumentationArticle } from './types';
import * as bodies from './documentationBodies';

export const DOCUMENTATION_ARTICLES: DocumentationArticle[] = [
  {
    id: 'overview',
    categoryId: 'getting-started',
    navOrder: 0,
    title: 'What is Kanban AI?',
    excerpt: 'Product surfaces, mental model, and where to go next on this board.',
    estimatedMinutes: 4,
    tags: ['overview', 'product'],
    date: '2026-04-01',
    author: 'Kanban AI',
    body: bodies.bodyOverview,
  },
  {
    id: 'guest-board-vs-account',
    categoryId: 'getting-started',
    navOrder: 1,
    title: 'Guest board vs signed-in account',
    excerpt: 'Local-only playthroughs vs cloud-backed projects—storage, features, and when to authenticate.',
    estimatedMinutes: 6,
    tags: ['guest', 'account', 'storage'],
    date: '2026-04-02',
    author: 'Kanban AI',
    body: bodies.bodyGuestVsAccount,
  },
  {
    id: 'creating-your-first-project',
    categoryId: 'getting-started',
    navOrder: 2,
    title: 'Creating your first project',
    excerpt: 'Blank board or AI chat builder: live workspace, then create the board when ready.',
    estimatedMinutes: 5,
    tags: ['setup', 'roadmap', 'AI'],
    date: '2026-04-03',
    author: 'Kanban AI',
    body: bodies.bodyFirstProject,
  },
  {
    id: 'faq-and-troubleshooting',
    categoryId: 'getting-started',
    navOrder: 3,
    title: 'FAQ & troubleshooting',
    excerpt: 'Quick answers on guest data, AI scope, sharing, indexing, and local development.',
    estimatedMinutes: 5,
    tags: ['faq', 'support'],
    date: '2026-04-04',
    author: 'Kanban AI',
    body: bodies.bodyFaq,
  },
  {
    id: 'board-columns-tasks-and-sprints',
    categoryId: 'workspace',
    navOrder: 0,
    title: 'Board: columns, tasks & sprints',
    excerpt: 'Drag-and-drop workflow, card hygiene, and how focus ties to the active project.',
    estimatedMinutes: 8,
    tags: ['kanban', 'tasks', 'workflow'],
    date: '2026-04-02',
    author: 'Kanban AI',
    body: bodies.bodyBoardMechanics,
  },
  {
    id: 'ai-sidebar-and-task-chat',
    categoryId: 'ai',
    navOrder: 0,
    title: 'AI sidebar & task chat',
    excerpt: 'What the model sees, strong prompts, limitations, and privacy-minded usage.',
    estimatedMinutes: 9,
    tags: ['AI', 'chat', 'LLM'],
    date: '2026-04-03',
    author: 'Kanban AI',
    body: bodies.bodyAiChat,
  },
  {
    id: 'project-types-and-prompts',
    categoryId: 'ai',
    navOrder: 1,
    title: 'How AI reads your brief',
    excerpt: 'Domain is inferred from the brief—no type picker. How to steer roadmap and tasks.',
    estimatedMinutes: 5,
    tags: ['prompts', 'brief', 'AI'],
    date: '2026-04-04',
    author: 'Kanban AI',
    body: bodies.bodyProjectTypes,
  },
  {
    id: 'account-sync-and-data',
    categoryId: 'account',
    navOrder: 0,
    title: 'Account, sync & data stewardship',
    excerpt: 'Supabase-backed auth, what is stored, deletion/export expectations, and AI logging.',
    estimatedMinutes: 7,
    tags: ['Supabase', 'privacy', 'auth'],
    date: '2026-04-01',
    author: 'Kanban AI',
    body: bodies.bodyAccountData,
  },
  {
    id: 'sharing-a-public-board',
    categoryId: 'account',
    navOrder: 1,
    title: 'Sharing a public board',
    excerpt: 'Read-only links, safety checklist, and how public URLs differ from guest mode.',
    estimatedMinutes: 5,
    tags: ['sharing', 'public', 'security'],
    date: '2026-04-05',
    author: 'Kanban AI',
    body: bodies.bodySharing,
  },
  {
    id: 'invite-project-members',
    categoryId: 'account',
    navOrder: 2,
    title: 'Invite project members',
    excerpt: 'Add editors by email, Members panel, and how sharing differs from a public read-only link.',
    estimatedMinutes: 5,
    tags: ['collaboration', 'members', 'sharing'],
    date: '2026-07-07',
    author: 'Kanban AI',
    body: bodies.bodyInviteMembers,
  },
  {
    id: 'analytics-for-owners',
    categoryId: 'account',
    navOrder: 3,
    title: 'Analytics for owners',
    excerpt: 'Who can open the Analytics page, how guest activity is bucketed, and ethical use.',
    estimatedMinutes: 4,
    tags: ['analytics', 'owner', 'metrics'],
    date: '2026-04-06',
    author: 'Kanban AI',
    body: bodies.bodyAnalytics,
  },
  {
    id: 'local-development-and-environment',
    categoryId: 'developers',
    navOrder: 0,
    title: 'Local development & environment',
    excerpt: 'Clone, .env.local, npm run dev:local — or Supabase + vercel dev for production parity.',
    estimatedMinutes: 6,
    tags: ['Vite', 'Vercel', 'OpenAI', 'contributing'],
    date: '2026-04-07',
    author: 'Kanban AI',
    body: bodies.bodyLocalDev,
  },
  {
    id: 'landing-page-ab-test',
    categoryId: 'developers',
    navOrder: 2,
    title: 'Landing page A/B test',
    excerpt: 'Variant assignment, preview URLs, analytics dashboard, and bumping experiment version.',
    estimatedMinutes: 4,
    tags: ['analytics', 'marketing', 'experiments'],
    date: '2026-07-07',
    author: 'Kanban AI',
    body: bodies.bodyLandingAbTest,
  },
  {
    id: 'connect-mcp-claude-cursor',
    categoryId: 'developers',
    navOrder: 1,
    title: 'Connect Claude & Cursor (MCP)',
    excerpt: 'Wire Kanban AI into MCP clients: access token, Cursor config, Claude Desktop, tools, and troubleshooting.',
    estimatedMinutes: 8,
    tags: ['MCP', 'Cursor', 'Claude', 'integrations'],
    date: '2026-07-07',
    author: 'Kanban AI',
    body: bodies.bodyMcpConnect,
  },
];
